### ISSUE TITLE
What if we could query a PDF, f.eks ask it questions or ask it to generate revision questions

### ISSUE THREAD

**Issue by minfuel** [omagdy7/ollama-logseq#12]

**Comment by taweili** [comment]
Integrating with [LlamaIndex ](https://www.llamaindex.ai/) would provide the ability to interact with PDFs and other unstructured source. I am learningabout LlamaIndex and may integrate this into the plugin.

**Comment by omagdy7** [comment]
This is a good idea, but I don't how feasible it is practically for couple of reasons:

1. The small parameter AIs 7B and 13B from experience are very bad with large context windows and they start to hallucinate.
2. Processing power feeding a big PDF to one of those AIs I think would take a lot of computing power. 

However it's worth researching about it and taweili mentioned [LLamaIndex](https://www.llamaindex.ai/) which I've never heard about, but sounds promising

**Comment by BradKML** [comment]
Are there any lightweight models that has a strong context window? Heard Qwen has 32K or something while being around 3B. Currently finding solutions that works on integrated GPUs on laptops for travelling needs
Also @taweili are there other options than LlamaIndex + Support for multiple model types? Haystack?

**Comment by taweili** [comment]
> Are there any lightweight models that has a strong context window? Heard Qwen has 32K or something while being around 3B. Currently finding solutions that works on integrated GPUs on laptops for travelling needs Also @taweili are there other options than LlamaIndex + Support for multiple model types? Haystack?

RAG is better solution than big context window LLM in term of chatting with PDF. I plan to try llamaindex TS for Logseq plugin when I have time.

**Comment by omagdy7** [comment]
@BradKML I think there are already dedicated better tools for chatting with PDFs. And it's outside the scope of this plugin

**Comment by BradKML** [comment]
@omagdy7 noted for being out of scope but would like @taweili to see if there are ways to make the integration across apps to work better than Khoj and GPT4All. Thanks for all
