### ISSUE TITLE
Feature request: Ask in the context of the block and not whole page

### ISSUE THREAD

**Issue by AvijeetPrasad** [omagdy7/ollama-logseq#15]
Thanks a lot for this useful plugin. Currently, the only way to ask in the context of a block is to `prompt from the block`. It would be nice to get an option to ask AI with block context. This would help us a lot when working with bigger pages when we want a block-specific query.

**Comment by omagdy7** [comment]
So just to make sure I am following you want something like Ask Ai with context but it feeds only the current block context right?

**Comment by AvijeetPrasad** [comment]
> So just to make sure I am following you want something like Ask Ai with context but it feeds only the current block context right?

Yes. That's correct. It takes the input from the current block including any child blocks under it, but not the rest of the page.

**Comment by taweili** [comment]
> > So just to make sure I am following you want something like Ask Ai with context but it feeds only the current block context right?
> 
> Yes. That's correct. It takes the input from the current block including any child blocks under it, but not the rest of the page.

It's not hard to include the child blocks as part of the context in query to Ollama but as now the response from Ollama is also added as the child block, they should be excluded? I am trying to figure out a better interaction before doing this.

**Comment by omagdy7** [comment]
Done via [481ae0c](https://github.com/omagdy7/ollama-logseq/commit/481ae0c24785a1798a0445a2a982acce6db7e4f2)
