### ISSUE TITLE
can ollama-context-menu do "summarize from block"

### ISSUE THREAD

**Issue by happy15** [omagdy7/ollama-logseq#17]
Hi, I tried to add an ollama-context-menu setting to summarize the whole content from a block including its children. Below is my setting:

```
ollama-context-menu-title:: Ollama: 总结整个block包括children
ollama-prompt-prefix:: summarize the text with bullet points like I am 5:
```

But it seems it just processes the content from the block only.

How can I do it? Thanks in advance.

**Comment by omagdy7** [comment]
Thanks for submitting this issue I just rolled out a new update that should fix this issue

**Comment by happy15** [comment]
verified and it works. 👍
