### ISSUE TITLE
Couldn't fulfill request make sure you don't have a typo in the name of the model or the host url

### ISSUE THREAD

**Issue by technicolourdream** [omagdy7/ollama-logseq#3]
Whenever I try to use this plugin i recieve this error notification from Logseq, Im using Mistral with Ollama.

"Couldn't fulfill request make sure you don't have a typo in the name of the model or the host url"

And these are my settings from the plugin I didnt change anything:

localhost:11434
mistral:instruct

**Comment by omagdy7** [comment]
In plugins hit the gear icon and check package.json and make sure effect is set to true, and did you make sure that you can run the model normally without logseq with ollama run mistral:instruct?
