### ISSUE TITLE
Ollama doesn't work in default journal

### ISSUE THREAD

**Issue by 0nxku** [omagdy7/ollama-logseq#4]
When you're trying to use Ollama in "Journals", in which you have a list of all your dates, it just doesn't work.
But it works when you open a specific journal page.

**Comment by omagdy7** [comment]
Yeah I am aware of that and apparently the API treats the journal page differently I will try to address that in the next release

**Comment by aidfulAI** [comment]
Thanks @omagdy7 for creating ollama-logseq. Really appreciate it!

I started to test the ask with context on a journal page and thought there was something fundamentally wrong. Thanks to the issue from @0nxku, I realized that it is only broken in the journal.

Looking forward to an update which fixes this.

**Comment by taweili** [comment]
I think only few functions in ollama-logseq that having problems with journal page. I have been adding functions to the plugin to be centered around blocks. These functions work fine with the journal page. 

> Thanks @omagdy7 for creating ollama-logseq. Really appreciate it!
> 
> I started to test the ask with context on a journal page and thought there was something fundamentally wrong. Thanks to the issue from @0nxku, I realized that it is only broken in the journal.
> 
> Looking forward to an update which fixes this.

**Comment by omagdy7** [comment]
Apparently this issue is fixed now for me so I will mark close this issue
