### ISSUE TITLE
there's nothing when I open http://localhost:5173/ 

### ISSUE THREAD

**Issue by thesanju** [omagdy7/ollama-logseq#5]
I installed all packages with pnpm and started npm run dev but there's nothing in http://localhost:5173/

**Comment by omagdy7** [comment]
I don't understand do you want to develop the plugin? if so you just open logseq and load the plugin after installing dependencies and running pnpn dev and you it should work and make sure you use pnpm in install and run.

If you don't want to develop the plugin you just download it from the marketplace

**Comment by thesanju** [comment]
Sorry man I misunderstood, thanks for clarifying.
