### ISSUE TITLE
Request: Retain Prompt

### ISSUE THREAD

**Issue by mtremoulet** [omagdy7/ollama-logseq#6]
Awesome stuff. It would be nice if Ask AI or Ask with Context retained the prompt and not just the result - helpful when I go back to remember what I asked for and why I have the block of text.

Example output of /ask How do I jumpstart a car?

* _How do I jumpstart a car?_
1. Turn off the ignition and remove the key from the car.
2. Connect the positive terminal of the battery to the red jumper cable.
3. Connect the other end of the jumper cable to the other red battery terminal on the other car.
[et cetera]

**Comment by omagdy7** [comment]
Closed with  [#d136b85](https://github.com/omagdy7/ollama-logseq/commit/d136b8546517e5a910d953bc16f8393044f0a6c9)
